# Generated by Django 4.1 on 2022-09-01 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="recipes",
            field=models.ManyToManyField(related_name="tags", to="main.recipe"),
        ),
    ]
