# Generated by Django 4.1 on 2022-09-16 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_recipe_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="Time",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Additional", "Additional"),
                            ("Cook", "Cook"),
                            ("Preparation", "Preparation"),
                            ("Total", "Total"),
                        ],
                        max_length=20,
                    ),
                ),
                ("days", models.PositiveIntegerField(blank=True, null=True)),
                ("hours", models.PositiveIntegerField(blank=True, null=True)),
                ("minutes", models.PositiveIntegerField(blank=True, null=True)),
                ("note", models.CharField(blank=True, default="", max_length=64)),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_times",
                        to="main.recipe",
                    ),
                ),
            ],
        ),
    ]
