# Generated by Django 4.1 on 2022-09-18 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="time",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="times",
                to="main.recipe",
            ),
        ),
    ]
