# Generated by Django 4.1.1 on 2022-09-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_recipe_servings"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
