# Generated by Django 4.1.2 on 2022-10-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_direction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="direction",
            name="description",
            field=models.TextField(),
        ),
    ]
