# Generated by Django 4.1.2 on 2022-10-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_alter_direction_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="direction",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name="direction",
            unique_together={("order", "recipe")},
        ),
    ]
