# Generated by Django 4.1.2 on 2022-10-07 20:40

from django.db import migrations, models
import django.db.models.constraints


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_direction_order_alter_direction_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="direction",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="direction",
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                fields=("order", "recipe"),
                name="direction_unique_order_recipe",
            ),
        ),
    ]
